-- RenameEnumValues
ALTER TYPE "AuctionCategory" RENAME VALUE 'VEICULOS' TO 'VEHICLES';
ALTER TYPE "AuctionCategory" RENAME VALUE 'IMOVEIS' TO 'PROPERTIES';
ALTER TYPE "AuctionCategory" RENAME VALUE 'ELETRONICOS' TO 'ELECTRONICS';
ALTER TYPE "AuctionCategory" RENAME VALUE 'OUTROS' TO 'OTHERS';
